version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:./app
    depends_on:
      - db
    command: cd ~/app/gunicorn-master/project_atom_app && gunicorn --workers=2 test_falcon:app
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3316:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: developer
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: gunicorn
